### ISSUE TITLE
build/lib is not included in npm package

### ISSUE THREAD

**Issue by bengarnett** [vercel/micro#10]
D:>micro
module.js:341
    throw err;
    ^

Error: Cannot find module '../lib'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\micro\buil
d\bin\micro:10:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by bengarnett** [comment]
**worked around by cloning git to build and copy the file manually but**

**(2) "gulp" failed**

d:\code\microtest\git\micro>gulp
[20:06:54] Using gulpfile d:\code\microtest\git\micro\gulpfile.js
[20:06:54] Starting 'lint'...
[20:06:54] Starting 'compile-bin'...
[20:06:54] Starting 'compile-test'...
[20:06:54] Starting 'compile-lib'...
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (d:\code\microtest\git\micro\node_modules\babel-eslint\index.
js:220:40)
    at Object.exports.parse (d:\code\microtest\git\micro\node_modules\babel-esli
nt\index.js:399:5)
    at parse (d:\code\microtest\git\micro\node_modules\eslint\lib\eslint.js:512:
27)
    at EventEmitter.module.exports.api.verify (d:\code\microtest\git\micro\node_
modules\eslint\lib\eslint.js:646:19)
    at processText (d:\code\microtest\git\micro\node_modules\eslint\lib\cli-engi
ne.js:230:27)
    at CLIEngine.executeOnText (d:\code\microtest\git\micro\node_modules\eslint\
lib\cli-engine.js:686:26)
    at verify (d:\code\microtest\git\micro\node_modules\gulp-eslint\index.js:20:
23)
    at Transform._transform (d:\code\microtest\git\micro\node_modules\gulp-eslin
t\index.js:68:18)
    at Transform._read (_stream_transform.js:166:10)
    at Transform._write (_stream_transform.js:154:12)

**although "gulp test" worked and includes build**

this allowed me to copy the file

D:\code\microtest>micro

> Error! Please supply a file.

  Usage: micro [options]

  Options:

```
-h, --help         output usage information
-V, --version      output the version number
-p, --port <port>  Port to listen on (3000)
-n, --no-babel     Skip Babel transformation
```

**But (3)**

D:\code\microtest>micro -p 3000 app.js
module.js:341
    throw err;
    ^

Error: Cannot find module './C:\Program Files (x86)\nodejs\node_modules\micro\no
de_modules\babel-runtime\package.json\regenerator'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\code\microtest\app.js:3:20)
    at Module._compile (module.js:413:34)
    at loader (C:\Program Files (x86)\nodejs\node_modules\micro\node_modules\bab
el-register\lib\node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js](C:Program Files
 %28x86%29nodejsnode_modulesmicronode_modulesbabel-registerlibnode.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

node v 5.5.0
npm 2.14.17
windows 8

**Comment by rauchg** [comment]
Uhm, seems like a Windows-only issue. Not sure what could be causing it.

**Comment by jpoon** [comment]
`micro` installed from npm was fine, but I get a similar error with babel-runtime when I try running it: 

```
> npm install -g micro
> micro -p 3000 sleep.js

module.js:340
    throw err;
    ^

Error: Cannot find module './C:\Users\jason\AppData\Roaming\nvm\v4.2.4\node_modules\micro\node_modules\babel-runtime\package.json\regenerator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Coding\sleep.js:3:20)
    at Module._compile (module.js:435:26)
    at loader (C:\Users\jason\AppData\Roaming\nvm\v4.2.4\node_modules\micro\node_modules\babel-register\lib\node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\jason\AppData\Roaming\nvm\v4.2.4\node_modules\micro\node_modules\babel-register\lib\node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```
- Windows 10
- node v4.2.4
- npm 2.14.12

Curious as to why it's adding that extra `package.json` into the path when trying to find the regenerator module...

**Comment by rauchg** [comment]
OH! it's my hack to make `babel-runtime` work from anywhere.

**Comment by rauchg** [comment]
@bengarnett can you check with `1.0.2`?

**Comment by bengarnett** [comment]
with 1.0.2 the install/lib issue is gone, but I still last issue

D:\code\microtest>micro -p 3000 sleep.js
module.js:341
    throw err;
    ^

Error: Cannot find module './C:\Program Files (x86)\nodejs\node_modules\micro\no
de_modules\babel-runtime\package.json\regenerator'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\code\microtest\sleep.js:3:20)
    at Module._compile (module.js:413:34)
    at loader (C:\Program Files (x86)\nodejs\node_modules\micro\node_modules\bab
el-register\lib\node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js](C:Program Files
 %28x86%29nodejsnode_modulesmicronode_modulesbabel-registerlibnode.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by rauchg** [comment]
Sorry, it's `1.0.3` that should fix it. Please confirm.

**Comment by bengarnett** [comment]
still seeing Cannot find module './C:\Program Files (x86)\nodejs\node_modules\micro\no
de_modules\babel-runtime\package.json\regenerator' at runtime in 1.0.3

**Comment by bengarnett** [comment]
Actually this does work now for the common case. Where it doesn't work is because I had the app on drive D and the path resolver fails when trying to run the micro globally installed on C: drive.

Running the app from C drive solved my remaining issue. Thanks for the help!
