### ISSUE TITLE
npm package is out of date

### ISSUE THREAD

**Issue by jameshfisher** [vercel/micro#455]
[The latest npm package](https://www.npmjs.com/package/micro) is 9.3.4. It seems to have no TypeScript declarations. However, [there are TypeScript declarations on the master branch](https://github.com/vercel/micro/blob/master/packages/micro/micro.d.ts), committed almost 3 years ago.

**Comment by jameshfisher** [comment]
Is the recommendation to use [`@types/micro`](https://www.npmjs.com/package/@types/micro) instead? It says it's for v7, so two major versions old.

**Comment by jameshfisher** [comment]
(n.b.: I'm only reluctantly using this package because [NextJS has no convenient way to get the request body as a buffer](https://github.com/vercel/next.js/discussions/13405))

**Comment by Bessonov** [comment]
@jameshfisher you can use `9.3.5-canary.3`. 

@leerob is there a plan to release `9.4.0`?

**Comment by leerob** [comment]
@jameshfisher FYI https://github.com/vercel/next.js/discussions/27702#discussioncomment-2929911

**Comment by jameshfisher** [comment]
Thanks @leerob, that's much nicer! 😍

**Comment by Bessonov** [comment]
> @jameshfisher FYI [vercel/next.js#27702 (comment)](https://github.com/vercel/next.js/discussions/27702#discussioncomment-2929911)

If I understand this correctly, then the one caution about this is that you can consume the body only once. Micro uses a [WeakMap for caching](https://github.com/vercel/micro/blob/master/packages/micro/lib/index.js#L146) for this reason.

**Comment by leerob** [comment]
Closing as this is addressed 🙏

**Comment by tonyxiao** [comment]
It's not address given that the types aren't released just yet. What's blocking the 9.4.0 release?

**Comment by Bessonov** [comment]
Still not released, see Versions: https://www.npmjs.com/package/micro .

**Comment by leerob** [comment]
Done: https://github.com/vercel/micro/releases/tag/9.4.0
